import { Remetente } from './remetente';
import { Especie } from './especie';
import { Login } from './login';
import { EspecieMorcego } from './especie-morcego';
import { Municipio } from './municipio';
import { Raca } from './raca';

export interface Principal {
    id: number;
    alimentacao: string;
    dataentrada: number;
    dataresultado1: number;
    dataresultado2: number;
    diferencial: string;
    eeb: boolean;
    endereco: string;
    fecharresultado1: boolean;
    fecharresultado2: boolean;
    formin: string;
    hora: number;
    idade: string;
    namostra: number;
    natamostra: string;
    obs: string;
    observacoes: string;
    pelagem: string;
    proprietario: string;
    registro: string;
    remetente: string;
    resultado1: string;
    resultado2: string;
    sexo: string;
    sivcont: boolean;
    ultimaatualizacao: number;
    usuario: string;
    agressao: boolean;
    contato: boolean;
    datacolheita: number;
    contatoagressao: boolean;
    materialanalisadoifd: string;
    materialanalisadopb: string;
    observacoespb: string;
    especieid: Especie;
    especiemorcegoid: EspecieMorcego;
    recebeuid: Login;
    ultimousuario: Login;
    veterinarioresponsavel1: Login;
    veterinarioresponsavel2: Login;
    municipioid: Municipio;
    racaid: Raca;
    remetenteid: Remetente;
}
